[[wildfly_jar_introduction]]
## Introduction

The WildFly JAR Maven plugin is aimed to build a bootable JAR for WildFly (starting version 20.0.0.Final). 
A WildFly bootable JAR contains both the server and your packaged application (a JAR, an EAR or a WAR).
Once the application has been built and packaged as a bootable JAR, you can start the application using the following command:

```
java -jar target/myapp-bootable.jar
```

The _--help_ argument displays the list of the supported arguments:

```
java -jar target/myapp-bootable.jar --help
```

A WildFly bootable JAR behaves in a way that is similar to a WildFly server installed on file system:

* It supports the main standalone server startup arguments. 
* It can be administered/monitored using WildFly CLI.


Some limitations exist:

* The server can't be re-started automatically during a shutdown. The bootable JAR process will exit without restarting.
* Management model changes (eg: using WildFly CLI) are not persisted. Once the server is killed, management updates are lost.
* Server can't be started in _admin mode_.

NB: When started, the bootable JAR installs a WildFly server in the _TEMP_ directory. 
The bootable JAR displayed traces contain the actual path to this transient installation. This installation is deleted when the bootable JAR process exits.

[[wildfly_jar_examples]]
## Examples

The examples https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples[directory] 
contains Maven example projects that highlight various usages of the WildFly bootable JAR. Build and run these projects
to familiarize yourself with the Maven plugin. A good example to start with is the 
https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/jaxrs[jaxrs] example.

Some of these examples are targeting deployment of the bootable JAR in OpenShift. 
For example: https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/microprofile-config[microprofile-config], 
https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/postgresql[postgresql] and 
https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/jkube[jkube].

Deployment inside a https://github.com/GoogleContainerTools/jib[JIB] container is 
covered by https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/jib[jib] example and _examples/jib-*_ projects.

[[wildfly_jar_examples_download]]
### Downloading the examples

* Clone the wildfly-jar-maven-plugin repository: _git clone -b {project-branch} https://github.com/wildfly-extras/wildfly-jar-maven-plugin_

* _cd wildfly-jar-maven-plugin/examples_

* Each example directory contains a README file with instructions on how to build and run the example.


[[wildfly_jar_composing_custom_server_galleon]]
## Composing custom server with Galleon layers

When building a bootable JAR you have the ability to select the set of https://docs.wildfly.org/{wildfly-major}/Bootable_Guide.html#wildfly_layers[WildFly Galleon layers] 
you want to see present in the bootable JAR. Selecting a subset of server features has an impact on the server xml configuration 
and the set of installed JBoss modules. By selecting the subset required by your application you will reduce the JAR size, server configuration content and memory footprint.

You are not limited to the https://docs.wildfly.org/{wildfly-major}/Bootable_Guide.html#wildfly_layers[WildFly Galleon layers], you can combine other third parties Galleon layers compatible with 
WildFly (eg: https://github.com/wildfly-extras/wildfly-datasources-galleon-pack[WildFly database drivers and datasources layers]). 
The example https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/postgresql[postgresql] 
shows how to create a _cloud-server_ with support for _postgresql_ database.

[[wildfly_jar_composing_custom_server_galleon_version]]
### Specifying the WildFly server version to use

You need to provide a reference to the WildFly Galleon producer that contains the layers you want to use. This can be done in 3 ways.

[[wildfly_jar_composing_custom_server_galleon_fpl]]
#### Providing WildFly Galleon feature-pack location

That is the simplest way to reference a WildFly server. 
The configuration element link:#featurePackLocation[feature-pack-location] contains this information.

Some examples:

* To provision a WildFly {wildfly-major} server: 

[source,xml,subs=attributes+]
----
<feature-pack-location>wildfly@maven(org.jboss.universe:community-universe)#{wildfly-major}.0.0.Final</feature-pack-location>
----

* To provision the latest WildFly server: 

[source,xml,subs=attributes+]
----
<feature-pack-location>wildfly@maven(org.jboss.universe:community-universe)</feature-pack-location>
----

[[wildfly_jar_composing_custom_server_galleon_feature_packs]]
#### Providing a list of Galleon feature-packs

In some cases you will want to combine Galleon layers from multiple sources. In this case you will use the link:#featurePacks[feature-packs] configuration element that contains a list 
of feature-packs. For example, to provision Galleon layers from WildFly {wildfly-major} and WildFly extras datasources you would provide:

[source,xml,subs=attributes+]
----
<feature-packs>
    <feature-pack>
        <location>wildfly@maven(org.jboss.universe:community-universe)#{wildfly-major}.0.0.Final</location>
    </feature-pack>
    <feature-pack>
        <groupId>org.wildfly</groupId>
        <artifactId>wildfly-datasources-galleon-pack</artifactId>
        <version>1.0.6.Final</version>
    </feature-pack>
</feature-packs>
----

NB: The list of feature-packs can't be used in conjunction with link:#featurePackLocation[feature-pack-location] element.

[[wildfly_jar_composing_custom_server_galleon_provisioning_xml]]
#### Providing a Galleon provisioning.xml file

For advanced use cases you can fully control the Galleon provisioning by defining the file _galleon/provisioning.xml_. 
_galleon_ directory must be located in the root directory of your Maven project. A custom file location can be set 
thanks to the _provisioning-file_ plugin option. 

[[wildfly_jar_composing_custom_server_galleon_layers]]
### Specifying the set of Galleon layers to use

If no Galleon layers are provided, a microprofile standalone server (with a configuration identical to the 
default _standalone-microprofile.xml_ configuration) is provisioned and packaged in the bootable JAR. 
In order to reduce the server content to your application needs, use the link:#layers[layers] configuration element.

For example, to provision a server containing jaxrs and management support:

[source,xml]
----
<layers>
    <layer>jaxrs</layer>
    <layer>management</layer>
</layers>
----

[[wildfly_jar_composing_custom_server_galleon_exclude_layers]]
### Excluding Galleon layers

In order to exclude layers that are not strictly required, use the link:#excludedLayers[excluded-layers] configuration element.

For example, _jaxrs_ layer (that depends on _web-server_ layer) brings the deployment scanner. The deployment scanner being an optional dependency of the _web-server_ layer 
it can be excluded:

[source,xml]
----
<excluded-layers>
    <layer>deployment-scanner</layer>
</excluded-layers>
----

[[wildfly_jar_url_context]]
## URL context path of deployed application

By default, a WAR deployed inside a bootable JAR is located in the root context ('/'). This can be changed to the WAR file name by using the link:#contextRoot[context-root] configuration element.

[[wildfly_jar_hollow_jar]]
## Hollow bootable JAR

If your use-case requires it, you can create a bootable JAR that doesn't contain a deployment. It can be handy to re-use a bootable JAR artifact with various deployments.
Use the link:#hollowJar[hollow-jar] configuration element to create an hollow JAR.

The example https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/hollow-jar[hollow-jar] shows how to build an hollow JAR.

When starting an hollow JAR you can provide the path to a deployment you want to see deployed inside the server. For example:

``
 java -jar target/jaxrs-hollow-server-bootable.jar --deployment=path/to/my-jaxrs-app.war
``

NB: In order to have your deployment be located in the root context, name the WAR file _ROOT.war_.

[[wildfly_jar_configuring_build]]
## Configuring the server during packaging

In addition to Galleon layers that you can use to configure the server, you can fine tune the server during packaging.

The Maven plugin allows you to:

* Run https://docs.wildfly.org/{wildfly-major}/Admin_Guide.html#Command_Line_Interface[WildFly CLI] scripts (see https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/logging[logging] example to configure loggers).
* Add extra content that you want to see packaged in the server (eg: _standalone/configuration/application-users.properties_, _standalone/configuration/keystore.jks_, ...).
The example https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/https[https] shows how to package a keystore file in the bootable JAR.

NB: The configuration changes applied during packaging are persisted in the server configuration.

IMPORTANT: Using a custom appender as a `custom-handler` in the logging subsystem is not supported with the bootable JAR.
           This only applies to custom handlers defined on the root of the logging subsystem.

You can workaround this by supplying your own `logging.properties` and defining the path in the `boot-logging-config` configuration property.
An example can be seen in the https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/logging-json[logging-json]
example project.

[[wildfly_jar_configuring_build_cli]]
### WildFly CLI execution during packaging

Part of WildFly CLI command line tool has been integrated in the Maven plugin. The plugin supports execution of CLI script files with a limited set of CLI configuration items.

CLI script files are text files that contain a sequence of WildFly CLI commands. Commands can be CLI defined commands 
(some builtin commands allowing to achieve complex sequence of server operations) and generic management operations to be sent to the server. Some examples can
be found in WildFly administration guide https://docs.wildfly.org/{wildfly-major}/Admin_Guide.html#CLI_Recipes[CLI recipes chapter].

In the context of Bootable JAR, the script does not need to contain commands to connect to the server or start an embedded server. 
The Maven plugin handles that for you by starting an embedded server for each group of scripts.

The plugin allows you to execute multiple group of scripts with different CLI contexts. 
A group of scripts and its configuration are defined in a ```cli-session``` composed of:

* ```<script-files>```: the list of paths to script files .
* ```properties-file```: (optional) a path to a properties file that contains java properties that scripts can reference (using the syntax ```${my.prop}```). 
For example, a command that sets the public inet-address to the value of ```all.addresses``` system property looks like: ```/interface=public:write-attribute(name=inet-address,value=${all.addresses})```
* ```resolve-expressions```: (optional) a boolean indicating if system properties or 
expressions are resolved before sending the operation requests to the server. Value is ```true``` by default.

All scripts present in a ```cli-session``` are executed within a single CLI execution. An embedded server is started for each defined ```cli-session```.

NB: The scripts are executed in the order they are defined in the plugin configuration. 

CLI configuration example:

[source,xml]
----
<cli-sessions>
  <cli-session>
    <script-files>
        <script>../scripts/script1.cli</script>
    </script-files>
    <!-- We want the env variables to be resolved during server execution -->
    <resolve-expressions>false</resolve-expressions>
  </cli-session>
  <cli-session>
    <script-files>
        <script>../scripts/script2.cli</script>
    </script-files>
    <properties-file>../scripts/cli.properties</properties-file>
    <!-- We want the properties to be resolved during CLI execution (not actually needed, this is the default behavior) -->
    <resolve-expressions>true</resolve-expressions>
  </cli-session>
</cli-sessions>
----

[[wildfly_jar_configuring_cloud]]
## Configuring the server for cloud execution

The configuration item ```<cloud></cloud>``` allows to build a bootable JAR for cloud environment. By default the server is configured to run inside an OpenShift context.
Set the cloud child element ```<type>openshift|kubernetes</type>``` to select the targeted cloud platform.

The sever configuration is updated in order to properly operate in a cloud environment:

* If no Galleon layers are provisioned, the provisioned configuration is ```standalone-microprofile-ha.xml``` instead of ```standalone-microprofile.xml```.
* The ```microprofile-health``` (or ```health``` layer if the WildFly Galleon feature-pack doesn't define ```microprofile-health``` layer) and ```core-tools``` (that contains WildFly CLI) Galleon layers are provisioned. They are required for the  OpenShift probes and WildFly OpenShift Operator to properly operate.
* The public and private inet addresses are bound to the value of the ```HOSTNAME``` environment variable if defined (defined in OpenShift PODS).
* The management inet address is bound to the 0.0.0.0 inet address allowing for local (required by WildFly CLI) and remote access (required by OpenShift readiness and liveness probes).
* The http and https socket-bindings are bound to 0.0.0.0 inet address.
* The transaction subsystem id is set to the value of ```jboss.tx.node.id```.
* The ```jboss.tx.node.id``` system property, if not set, is set to the value of ```HOSTNAME``` environment variable if defined (defined in OpenShift PODS). The node name value
is truncated to a max of 23 characters in order for the transaction subsystem to properly operate. The last 23 characters are taken into account.
* The ```jboss.node.name``` system property, if not set, is set to the value of ```HOSTNAME``` environment variable if defined (defined in OpenShift PODS).  
* The server logs are printed to the console.
* jgroups subsystem is configured to use kubernetes.KUBE_PING jgroups protocol for both tcp (default stack) and udp. PING and MPING protocols are removed.
* It is possible to configure jgroups to use un-encrypted password authentication. Set the ```<cloud>``` child element ```<enable-jgroups-password>true|false</enable-jgroups-password>``` to enable authentication. 
NB: When authentication is enabled, the environment variable ```JGROUPS_CLUSTER_PASSWORD``` must be set.

Some examples:

Configure for OpenShift execution:

[source,xml]
----
<cloud/>
----

Configure for OpenShift execution with jgroups authentication enabled:

[source,xml,subs=attributes+]
----
<cloud>
  <enable-jgroups-password>true</enable-jgroups-password>
</cloud>
----

Configure for kubernetes execution:

[source,xml]
----
<cloud>
  <type>kubernetes</type>
</cloud>
----

[[wildfly_jar_cloud_jkube]]
### OpenShift Deployment using Eclipse JKube

https://github.com/eclipse/jkube[JKube Maven plugin] contains support for WildFly bootable JAR. The 
https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/jkube[jkube] example shows how to combine
WildFly bootable JAR and JKube Maven plugins in order to deploy an application on OpenShift. 

[[wildfly_jar_cloud_operator]]
### WildFly OpenShift Operator

The WildFly OpenShift Operator can be used to manage deployments based on image containing a WildFly bootable JAR.
At boot time, the WildFly bootable JAR dumps in the file ```/opt/jboss/container/wildfly-bootable-jar/install-dir``` its installation path.
This information is required by the WildFly OpenShift Operator to retrieve transaction logs and call into WildFly CLI.

IMPORTANT: When deploying WildFly bootable JAR using openjdk image it is strongly advised to set ```GC_METASPACE_SIZE=96```environment variable.
           


[[wildfly_jar_configuring_runtime]]
## Configuring the server at runtime

The server can be configured using WildFly management tooling (WildFly CLI, HAL web console, ...).

In an OpenShift context, the WildFly CLI tool can be retrieved in the bootable JAR installation directory (advertised in the ```/opt/jboss/container/wildfly-bootable-jar/install-dir``` file).

NB: Configuration changes are not persisted. Once the server is killed, management updates are lost.

[[wildfly_jar_other_goals]]
## Other Maven plugin goals

In addition the main link:#_package[package] goal used to build a bootable JAR, the following goals are available:

* link:#_dev[dev]: To build a bootable JAR in 'dev' mode.
* link:#_run[run]: To launch the bootable JAR foreground (blocking).
* link:#_start[start]: To launch the bootable JAR in background (non blocking).
* link:#_shutdown[shutdown]: To kill a running bootable JAR.

IMPORTANT: In order to shutdown a running bootable JAR (started with 'start' or 'dev' goals), 
           the 'management' Galleon layer must have been provisioned. That is required for the
           plugin to be able to access the running server management interface. 
           If that is not the case, the server would have to be killed.

Check the link:#_maven_plugin[Maven plugin documentation] for an exhaustive list of configuration elements usable with each goal.

[[wildfly_jar_dev_mode]]
## Development mode (dev mode)

When packaging a bootable JAR, a WildFly server is provisioned and customization (if any) is applied. Rebuilding a bootable JAR each time is time consuming
and slows down the application development process.

We offer 2 different dev goals:

### Development mode with source watching

In order to speed-up the development of your application, the Maven plugin offers a link:#_dev_watch[dev-watch] goal that builds and starts the bootable JAR only once then 
watch for changes in order to rebuild and redeploy your application.

The workflow to follow during development is:

* _mvn wildfly-jar:dev-watch_
** The plugin builds your application, build an hollow server bootable JAR and starts it, 
then monitors the projects to detect source files changes and rebuild/redeploy the application.
** The goal `dev-watch` is blocking. When done, type Ctrl-C in the console to stop the process.

Watch details:

* `war`, `jar` and `ejb` packaging are supported.
* Applications are deployed as exploded deployments. 
* Any change to the project build sources (default to `src/main/java`) implies a recompile, repackage and redeploy.
* Any change to the `src/main/webapp` implies a copy of the file in the exploded deployment and a redeploy.
* Any change to the default resources `src/main/resources` as well as configured resource directories in pom.xml implies a repackage and redeploy.
* Any change to the pom.xml file outside of the plugin configuration implies a recompile, repackage and redeploy.
* Any change to the plugin configuration implies rebuild/restart of the bootable JAR, recompile, repackage and redeploy.
* Any change to CLI scripts or CLI properties files implies rebuild/restart of the bootable JAR, recompile, repackage and redeploy.
* Any change to extra content directories implies rebuild/restart of the bootable JAR, recompile, repackage and redeploy.

Error handling:

The `dev-watch` goal will not exit on error. Errors are advertised in the console.

* Compilation errors are printed in the console. Fix the files, recompilation will occur.
* Re-build of bootable JAR errors (eg: usage of invalid Galleon layer) are printed in the console. Fix the pom.xml file, rebuild/restart and redeploy will occur.
* Server startup errors are printed in the console. Fix your application, the application will get redeployed.

Limitations:

* No support for multi modules.
* No support for resources filtering (include/exclude). The resources directory is watched fully, this means that some re-deploy could be started for resources
excluded from the project.

### Remote development mode with source watching

Sometimes it might be required to develop the application remotely, for example in a cloud environment. The workflow is the same as the one of link:#wildfly_jar_dev_mode[Development mode with source watching] and it is using the same `dev-watch` goal.
The only required changes is about configuring how to connect to the remote application using the management API.

So you have to configure your bootable jar to allow remote connection to the management interface.
For example such a script would create an account *admin/passW0rd!*

[source,bash]
----
/subsystem=elytron/security-domain=ManagementDomain:undefine-attribute(name=default-realm)
/subsystem=elytron/security-domain=ManagementDomain:list-remove(name=realms, index=0)
/subsystem=elytron/properties-realm=ManagementRealm:remove
/subsystem=elytron/filesystem-realm=ManagementRealm:add(path=management-realm, relative-to=jboss.server.config.dir)
reload --start-mode=admin-only
/subsystem=elytron/filesystem-realm=ManagementRealm:add-identity(identity=admin)
/subsystem=elytron/filesystem-realm=ManagementRealm:add-identity-attribute(identity=admin, name=groups, value=[admin])
/subsystem=elytron/filesystem-realm=ManagementRealm:set-password(identity=admin, clear={password=passW0rd!})
/subsystem=elytron/security-domain=ManagementDomain:list-add(name=realms, index=0, value={realm=ManagementRealm})
/subsystem=elytron/security-domain=ManagementDomain:write-attribute(name=default-realm, value=ManagementRealm
----

So once you have your application running you can execute the goal locally like this:
[source,bash]
----
mvn  org.wildfly.plugins:wildfly-jar-maven-plugin:dev-watch\
        -Dwildfly.bootable.remote=true\
        -Dwildfly.hostname=microprofile-config-bootable-management-ehugonne1-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com\
        -Dwildfly.port=443\
        -Dwildfly.bootable.remote.protocol=remote+https\
        -Dwildfly.bootable.remote.username=admin\
        -Dwildfly.bootable.remote.password=passW0rd!
----

Error handling:

The `dev-watch` goal will not exit on error. Errors are advertised in the console.

* Compilation errors are printed in the console. Fix the files, recompilation will occur.
* Server related errors are printed on the server itself.

Limitations:

* No support for multi modules.
* No support for resources filtering (include/exclude). The resources directory is watched fully, this means that some re-deploy could be started for resources
excluded from the project.
* No support for complete rebuild of the server: you can't expect cli scripts or layer changes to be taken into account. You would need to rebuild the full bootable jar and relaunch it.

### Development mode with repackaging

In order to speed-up the development of your application, the Maven plugin offers a link:#_dev[dev] goal that builds and starts the bootable JAR only once.

The workflow to follow during development is:

* _mvn wildfly-jar:dev_
** The plugin builds an hollow server bootable JAR and starts it. The server uses the deployment scanner to monitor the _target/deployments_ directory in which 
your application will be copied during packaging.
* _mvn package -Ddev_
** Note the _-Ddev_ system property passed to the _package_ goal. This informs the plugin to skip creation of the bootable JAR and to copy your application to _target/deployments_ directory. 
The running server detects the application and deploys it.
* Do changes in your application code.
* _mvn package -Ddev_
** Once your application is built, the plugin copies it to the _target/deployments_ directory. The running server detects the updated application and re-deploys it.
* When done, kill the server: _mvn wildfly-jar:shutdown_
* When you are done with your application, create the final packaging by calling: _mvn package_

NB: Although the _dev_ mode relies on the deployment scanner, you can safely exclude it from the set of layers. 
The Maven plugin forces its presence when the server is started in _dev_ mode.

[[wildfly_jar_enabling_debug]]
## Enabling debug

You can enable debug by passing the _-agentlib:jdwp_ argument, for example:

```
java -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n -jar myapp-bootable.jar 
```

When using 'dev', 'run' or 'start' goals you can set the _jvmArguments_ configuration element to contain the same argument, for example:

[source,xml]
----
<configuration>
  <jvmArguments>
    <arg>-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n</arg>
  </jvmArguments>
</configuration>
----

[[wildfly_jar_enabling_debug_openshift]]
### Enable Debug for Openshift

When using the ```registry.redhat.io/ubi8/openjdk-11``` docker image to run a bootable JAR, you must set the following env variables to enable debug:

* JAVA_DEBUG=true
* JAVA_DEBUG_PORT=8787

Then enable port forwarding:

* oc get pods
* oc port-forward <pod name> 8787:8787

Finally, you can attach your debugger to 127.0.0.1:8787

[[wildfly_jar_advanced]]
## Advanced usages

[[wildfly_jar_advanced_slim]]
### Provisioning a slim bootable JAR

A _slim bootable JAR_ is a JAR that doesn't contain JBoss modules JAR files. The JBoss modules JAR files are retrieved from the local Maven repository.
Such slim bootable JAR is much smaller and starts faster.

To enable slim bootable JAR use the link:#pluginOptions[plugin-options] configuration element and add to it the _jboss-maven-dist_ element. For example:

[source,xml]
----
<plugin-options>
    <jboss-maven-dist/>
</plugin-options>
----

When running a slim bootable JAR, the default local Maven repository is used to resolve JBoss modules artifacts 
(in your development environment it shouldn't require special setup to start the bootable JAR).

This can be overridden by using the _-Dmaven.repo.local=<path to repository>_ when launching the server, for example:

```
java -Dmaven.repo.local=/opt/maven/maven-repo -jar jaxrs-bootable.jar
```

[[wildfly_jar_advanced_slim_repo_gen]]
#### Generating a Maven local repository during packaging

The Maven plugin can generate a Maven repository directory containing all the JBoss modules artifacts required by the slim bootable JAR. The generated Maven repository allows to 
run a slim bootable JAR in a context were no local Maven cache is present. 

To enable slim bootable JAR Maven repository generation, use the link:#pluginOptions[plugin-options] configuration element and add to it the _jboss-maven-dist_ and 
_jboss-maven-repo_ elements. For example:

[source,xml]
----
<plugin-options>
    <jboss-maven-dist/>
    <jboss-maven-repo>target/my-maven-repo</jboss-maven-repo>
</plugin-options>
----

In this example, the directory _<project directory>/target/my-maven-repo_ is created and contains the set of JBoss modules JAR required to start the server.
 
The https://github.com/wildfly-extras/wildfly-jar-maven-plugin/tree/{project-branch}/examples/slim[slim] example shows how to build a slim bootable JAR 
and generate a local Maven repository used at startup.

[[wildfly_jar_advanced_channels_provisioning]]
### Provisioning with WildFly Channels

It is possible to configure the plugin to use https://github.com/wildfly-extras/wildfly-channel[WildFly channels]. WildFly Channel yaml files URL and/or Maven Coordinates 
(version being optional) can be set thanks to the `<channels>` configuration item.

[source,xml]
----
<channels>
    <channel>
      <manifest>
        <url>file://${project.basedir}/my-channel.yaml</url>
      </manifest>
    </channel>
    <channel>
      <manifest>
        <!-- Use latest channel version -->
        <groupId>org.foo.bar</groupId>
        <artifactId>my-channel</artifactId>
        <!-- Uncomment to use a specific channel version -->
        <!--<version>2.0.0.Final</version>-->
      </manifest>
    </channel>
</channels>
----

[[wildfly_jar_troubleshooting]]
## Troubleshooting

### Out of Memory error when building

When building a large number of projects in the same Maven session you can encounter OOM error, this can be solved in various ways:

* You can increase the metaspace size of the Maven execution by setting the ```MAVEN_OPTS="-XX:MaxMetaspaceSize=<value>"``` environment variable.
* Or you can configure the plugin to fork part of its execution in remote processes:
[source,xml]
----
<configuration>
  ...
  <plugin-options>
    <jboss-fork-embedded>true</jboss-fork-embedded>
  </plugin-options>
</configuration>
----
